const MINUTE = 60 * 1000

const MAX_ITEMS_PER_REQUEST = 10000
const MAX_REQUESTS_PER_MINUTE = 90
const THROTTLE = Math.ceil(MINUTE / MAX_REQUESTS_PER_MINUTE)
const DEFAULT_ITEMS_LIMIT = 1000

module.exports = {
  MINUTE,
  MAX_ITEMS_PER_REQUEST,
  MAX_REQUESTS_PER_MINUTE,
  DEFAULT_ITEMS_LIMIT,
  THROTTLE
}
