const MINUTE = 60 * 1000

const MAX_ITEMS_PER_REQUEST = 10000
const MAX_REQUESTS_PER_MINUTE = 1000
const DEFAULT_ITEMS_LIMIT = 1000

module.exports = {
  MINUTE,
  MAX_ITEMS_PER_REQUEST,
  MAX_REQUESTS_PER_MINUTE,
  DEFAULT_ITEMS_LIMIT
}
